# Docs:
# https://aka.ms/yaml

trigger:
  - master
name: $(Rev:.r)
pool:
  name: Hosted Ubuntu 1604
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env'

- task: Bash@3
  displayName: "Set build number"
  inputs:
    filePath: 'ci/set-build-pipeline-name.sh'

- task: PowerShell@2
  displayName: 'Run tests'
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name Pester -Force -Verbose -Scope CurrentUser
      Invoke-Pester ./ci -OutputFormat NUnitXml -OutputFile ./TEST-CI.xml -EnableExit
    failOnStderr: true
    pwsh: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit
    failTaskOnFailedTests: true
  condition: always()

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     deployments/**
     roles/**
     scripts/**
     templates/**
     tests/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
