# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: Hosted Ubuntu 1604
steps:
- task: PowerShell@2
  displayName: 'Run tests'
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name Pester -Force -Verbose -Scope CurrentUser
      Invoke-Pester ./ci -OutputFormat NUnitXml -OutputFile ./TEST-CI.xml -EnableExit
    failOnStderr: true
    pwsh: true


- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit
    failTaskOnFailedTests: true
  condition: always()

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     deployments/**
     roles/**
     scripts/**
     templates/**
     tests/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
