#
# Build for the RPE PoCs AKS Cluster
#
name: RPE AKS RBAC Enabled Pipeline
trigger: none
pr: none
variables:
  aksResourceGroup: ''
  aksVnetCidr: ''
  aksSubnetCidr: ''
  aksServiceCidr: ''
  aksDnsServiceIp: ''
  keyvaultName: rpe-infra
  serviceConnection: azurerm-rpetemp
  helmVersion: '2.12.0'
  location: 'UK South'
  acrName: rpedev
  adminNamespace: 'admin'

jobs:
- job: Keyvault
  pool:
    vmImage: 'Ubuntu 16.04'
    name: hmcts-agent-pool #TODO: change to hosted when merged
  steps:
  - task: AzureKeyVault@1
    displayName: 'Get secrets from Keyvault'
    inputs:
      azureSubscription: $(serviceConnection)
      keyVaultName: $(keyvaultName)
      secretsFilter: 'aks-sp-id,aks-sp-secret,aks-sapp-secret,slack-webhook-url'
  - script: |
      echo "##vso[task.setvariable variable=aksServicePrincipalId;isOutput=true]$(aks-sp-id)"
      echo "##vso[task.setvariable variable=aksServicePrincipalSecret;isOutput=true]$(aks-sp-secret)"
      echo "##vso[task.setvariable variable=aksServerAppSecret;isOutput=true]$(aks-sapp-secret)"
      echo "##vso[task.setvariable variable=slackWebhookUrl;isOutput=true]$(slack-webhook-url)"
    displayName: 'Export Keyvault Variables'
    name: exportKeyvault

- job: DeployAKS
  dependsOn: Keyvault
  pool:
    vmImage: 'Ubuntu 16.04'
    name: hmcts-agent-pool #TODO: change to hosted when merged
  variables:
    aksClusterName: $(aksResourceGroup)-cluster
    aksServicePrincipalId: $[dependencies.Keyvault.outputs['exportKeyvault.aksServicePrincipalId']]
    aksServicePrincipalSecret: $[dependencies.Keyvault.outputs['exportKeyvault.aksServicePrincipalSecret']]
    aksServerAppSecret: $[dependencies.Keyvault.outputs['exportKeyvault.aksServerAppSecret']]
    slackWebhookUrl: $[dependencies.Keyvault.outputs['exportKeyvault.slackWebhookUrl']]
  steps:

  - task: AzureCLI@1
    displayName: Check VNET prerequisites
    inputs:
      azureSubscription: $(serviceConnection)
      arguments: $(aksResourceGroup) $(aksVnetCidr) $(aksSubnetCidr)
      scriptPath: scripts/check-vnet-prerequisites.sh

  - task: AzureResourceGroupDeployment@2
    displayName: 'Deploy VNET'
    condition: not(variables['aksSubnetId'])
    inputs:
      azureSubscription: $(serviceConnection)
      action: 'Create Or Update Resource Group'
      resourceGroupName: $(aksResourceGroup)
      deploymentMode: 'Incremental'
      location: $(location)
      templateLocation: 'Linked artifact'
      csmFile: 'templates/arm-vnet-template.json'
      overrideParameters: '-aksVnetName $(aksClusterName) 
        -aksVnetPrefix $(aksVnetCidr) 
        -aksSubnetName default 
        -aksSubnetPrefix $(aksSubnetCidr)'
      deploymentOutputs: 'vnetOutputs'

  - task: Bash@3
    displayName: Parse ARM Outputs
    condition: not(variables['aksSubnetId'])
    inputs:
      targetType: inline
      failOnStderr: false
      script: |
        for row in $(echo '$(vnetOutputs)' | jq -c '. | to_entries[]'); do
          outputName=$(echo ${row} | jq -r ".key")
          outputValue=$(echo ${row} | jq -r ".value.value")
          echo "##vso[task.setvariable variable=${outputName}]${outputValue}"
        done

  - task: AzureResourceGroupDeployment@2
    displayName: 'Deploy AKS Cluster'
    inputs:
      azureSubscription: $(serviceConnection)
      action: 'Create Or Update Resource Group'
      resourceGroupName: $(aksResourceGroup)
      deploymentMode: 'Incremental'
      location: $(location)
      templateLocation: 'Linked artifact'
      csmFile: 'templates/arm-aks-template.json'
      csmParametersFile: 'templates/arm-aks-parameters.json'
      overrideParameters: '-aksClusterName $(aksClusterName) 
        -aksVnetSubnetId $(aksSubnetId) 
        -aksServiceCidr $(aksServiceCidr) 
        -aksDnsServiceIp $(aksDnsServiceIp) 
        -servicePrincipalSecret $(aksServicePrincipalSecret) 
        -serverAppSecret $(aksServerAppSecret)'

  - task: AzureCLI@1
    displayName: 'Obtain AKS Admin access token.'
    inputs:
      azureSubscription: $(serviceConnection)
      scriptLocation: 'inlineScript'
      inlineScript: |
        az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --admin

  - task: Bash@3
    displayName: 'Create Custom Namespaces'
    inputs:
      targetType: inline
      failOnStderr: false
      script: |
        kubectl apply -f deployments/namespaces.yaml

  - task: AzureCLI@1
    displayName: 'Bind admin role to "aks-cluster-admin" group'
    inputs:
      azureSubscription: $(serviceConnection)
      scriptLocation: 'inlineScript'
      inlineScript: |
        CLUSTER_GLOBAL_ADMINS_GROUP=$(az ad group list --query  "[?displayName=='aks-cluster-admins'].objectId" -o tsv)
        
        CLUSTER_ADMINS_GROUP_NAME="$(aksClusterName)-cluster-admins"
        CLUSTER_ADMIN_GROUP=$(az ad group list --query  "[?displayName=='${CLUSTER_ADMINS_GROUP_NAME}'].objectId" -o tsv)
        if [ -z "${CLUSTER_ADMIN_GROUP}" ]; then 
            echo "Cluster admin group doesn't exist, creating"
            CLUSTER_ADMIN_GROUP=$(az ad group create  --display-name ${CLUSTER_ADMINS_GROUP_NAME} --mail-nickname ${CLUSTER_ADMINS_GROUP_NAME} --query objectId -o tsv)
        fi
        
        cat roles/cluster-admin-role-binding.yaml | \
          sed -e 's@${CLUSTER_ADMIN_GROUP}@'"$CLUSTER_ADMIN_GROUP"'@' | \
          sed -e 's@${CLUSTER_GLOBAL_ADMINS_GROUP}@'"$CLUSTER_GLOBAL_ADMINS_GROUP"'@' | \
          kubectl apply -f -

  - task: AzureCLI@1
    displayName: 'Bind developers roles'
    inputs:
      azureSubscription: $(serviceConnection)
      scriptLocation: 'inlineScript'
      inlineScript: |
        kubectl apply -f roles/developers-log-reader-role.yaml
        DEVELOPERS_GROUP=$(az ad group list --query  "[?displayName=='developers'].objectId" -o tsv)
        if [ ! -z "${DEVELOPERS_GROUP}" ]; then          
          cat roles/developers-log-reader-binding.yaml | sed -e 's@${DEVELOPERS_GROUP}@'"$DEVELOPERS_GROUP"'@' | kubectl apply -f -
        fi

  - task: AzureResourceGroupDeployment@2
    displayName: 'Create Managed Identity for AKS'
    inputs:
      azureSubscription: $(serviceConnection)
      action: 'Create Or Update Resource Group'
      resourceGroupName: $(aksResourceGroup)
      deploymentMode: 'Incremental'
      location: $(location)
      templateLocation: 'Linked artifact'
      csmFile: 'templates/arm-mi-template.json'
      overrideParameters: '-resourceName $(aksClusterName)-mi'

  - task: HelmInstaller@0
    displayName: 'Install Helm Client $(helmVersion)'
    inputs:
        helmVersion: $(helmVersion)
        checkLatestHelmVersion: false
        installKubectl: false

  - task: Bash@3
    displayName: 'Install Tiller $(helmVersion)'
    inputs:
      targetType: inline
      failOnStderr: false
      script: |
        kubectl apply -f roles/helm-rbac-config.yaml
        helm init --wait --service-account tiller --tiller-image gcr.io/kubernetes-helm/tiller:v$(helmVersion) --history-max=5 --kube-context '$(aksClusterName)-admin'

  - task: Bash@3
    displayName: 'Template repositories.yaml secret'
    inputs:
      targetType: inline
      failOnStderr: true
      script: |
        sed -i -e 's/${ACR_NAME}/$(acrName)/g' \
               -e 's@${ACR_SERVICE_PRINCIPAL_ID}@'"$AKS_SP_ID"'@' \
               -e 's@${ACR_SERVICE_PRINCIPAL_SECRET}@'"$AKS_SP_SECRET"'@' \
          templates/repositories.yaml
    env:
      AKS_SP_ID: $(aksServicePrincipalId)
      AKS_SP_SECRET: $(aksServicePrincipalSecret)

  - task: Bash@3
    displayName: 'Create repositories.yaml secret'
    inputs:
      targetType: inline
      failOnStderr: false
      script: |
        kubectl -n admin delete secret flux-helm-repositories || true
        kubectl -n admin create secret generic flux-helm-repositories --from-file=templates/repositories.yaml

  - task: Bash@3
    displayName: 'Install Weave Flux'
    inputs:
      targetType: inline
      failOnStderr: false
      script: |
        helm repo add weaveworks https://weaveworks.github.io/flux
        helm upgrade flux weaveworks/flux --install --namespace admin -f deployments/weave-flux/values.yaml \
          --set "git.path=k8s/$(aksResourceGroup)-cluster\,k8s/common",git.label=$(aksResourceGroup)-cluster \
          --wait

  - task: Bash@3
    displayName: 'Template Kured secret'
    inputs:
      targetType: inline
      failOnStderr: true
      script: |
        sed -i -e 's@${SLACK_WEBHOOK_URL}@'"$SLACK_WEBHOOK_URL"'@' templates/kured/values.yaml
    env:
      SLACK_WEBHOOK_URL: $(slackWebhookUrl)

  - task: Bash@3
    displayName: 'Create Kured secret'
    inputs:
      targetType: inline
      failOnStderr: false
      script: |
        kubectl -n kured delete secret kured-values || true
        kubectl -n kured create secret generic kured-values --from-file=templates/kured/values.yaml

- job: RunTests
  dependsOn: DeployAKS
  pool:
    name: 'Hosted VS2017'
  steps:
  - task: AzurePowerShell@3
    displayName: 'Run tests'
    condition: always()
    inputs:
      azureSubscription: $(serviceConnection)
      azurePowerShellVersion: latestVersion
      scriptType: 'inlineScript'
      inline: "Invoke-Pester @{Path= '$(Build.SourcesDirectory)/tests/*.tests.ps1' ;Parameters = @{ResourceGroupName='$(aksResourceGroup)'}} -OutputFile $(Build.SourcesDirectory)/TEST-Peering.xml -OutputFormat NUnitXML -EnableExit"
      timeoutInMinutes: 1
      
  - task: PublishTestResults@2
    displayName: 'Publish Environment Test Results **/TEST-*.xml'
    condition: always()
    inputs:
      testResultsFormat: NUnit
      timeoutInMinutes: 1