kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-logs-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"] # to read logs you need to be able to read pods
  verbs: ["get", "list"] # without list, it would be hard to find your pod name to get logs
- apiGroups: [""] # required to make the vscode kubernetes plugin work
  resources: ["namespaces"]
  verbs: ["get", "list"]
  
