# For use with Preview environment
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ${DEVELOPERS_GROUP}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-edit-custom-resources
rules:
  - apiGroups:
      - 'keda.k8s.io'
    resources:
      - 'scaledobjects'
    verbs:
      - 'create'
      - 'update'
      - 'delete'
      - 'watch'
      - 'list'
      - 'get'
  - apiGroups:
      - 'servicecatalog.k8s.io'
    resources:
      - 'servicebindings'
      - 'serviceinstances'
      - 'serviceinstances/status'
    verbs:
      - 'create'
      - 'update'
      - 'delete'
      - 'watch'
      - 'list'
      - 'get'
  - apiGroups:
      - 'secrets-store.csi.x-k8s.io'
    resources:
      - 'secretproviderclasses'
    verbs:
      - 'create'
      - 'update'
      - 'delete'
      - 'watch'
      - 'list'
      - 'get'
  - apiGroups:
      - 'helm.fluxcd.io'
    resources:
      - 'helmreleases'
    verbs:
      - 'create'
      - 'update'
      - 'delete'
      - 'watch'
      - 'list'
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer-edit-custom-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer-edit-custom-resources
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: ${DEVELOPERS_GROUP}
