workers: 4
helm:
  versions: v3
git:
  pollInterval: 1m
  ssh:
    secretName: flux-git-deploy
configureRepositories:
  enable: true
  repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: hmctspublic
    url: https://hmctspublic.azurecr.io/helm/v1/repo
resources:
  limits:
    cpu: 1000m
    memory: 3072Mi
  requests:
    cpu: 500m
    memory: 1Gi
nodeSelector: {
   agentpool: adminpool
  }
tolerations: [
{
key: "pods",
operator: "Equal",
value: "admin",
effect: "NoSchedule"
}
  ]
