registry:
  acr:
    enabled: true
git:
  url: git@github.com:hmcts/cnp-flux-config
  pollInterval: 1m
  secretName: flux-git-deploy
additionalArgs:
  - --manifest-generation=true
syncGarbageCollection:
  enabled: true
resources:
  limits:
    cpu: 1000m
    memory: 3072Mi
  requests:
    cpu: 500m
    memory: 1Gi
memcached:
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 100Mi