registry:
  acr:
    enabled: true
git:
  url: git@github.com:hmcts/cnp-flux-config
  pollInterval: 1m
  secretName: flux-git-deploy
additionalArgs:
  - --manifest-generation=true
syncGarbageCollection:
  enabled: true
nodeSelector: {
   agentpool: adminpool
  }
tolerations: [
{
key: "pods",
operator: "Equal",
value: "admin",
effect: "NoSchedule"
}
  ]
